#!/bin/bash

cd mtx_files 
 wget https://suitesparse-collection-website.herokuapp.com/MM/Rothberg/cfd2.tar.gz
 wget https://suitesparse-collection-website.herokuapp.com/MM/Rothberg/gearbox.tar.gz
 wget https://suitesparse-collection-website.herokuapp.com/MM/Boeing/pwtk.tar.gz
 wget https://suitesparse-collection-website.herokuapp.com/MM/Boeing/bcsstk37.tar.gz
 wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_AFE/af_0_k101.tar.gz
 wget https://suitesparse-collection-website.herokuapp.com/MM/Schenk_ISEI/ohne2.tar.gz
 wget https://suitesparse-collection-website.herokuapp.com/MM/PARSEC/Si41Ge41H72.tar.gz
 wget https://suitesparse-collection-website.herokuapp.com/MM/Norris/lung2.tar.gz
 wget https://suitesparse-collection-website.herokuapp.com/MM/Norris/torso2.tar.gz
 wget https://suitesparse-collection-website.herokuapp.com/MM/Simon/venkat01.tar.gz
 wget https://suitesparse-collection-website.herokuapp.com/MM/Fluorem/PR02R.tar.gz

 while read matrix
 do
   mtx_name=`echo $matrix | cut -d',' -f2`
   tar xvf ${mtx_name}.tar.gz
   mv ${mtx_name}/${mtx_name}.mtx .
 done < ../matrix.ID.name

 rm -rf */
 rm *.tar.gz
cd -

